### ISSUE TITLE
Datapack issue with "tools.json"

### ISSUE THREAD

**Issue by 0-Requiem** [lobbienjonsji/Lobs-Metalworks-Issues#1]
I really like this mod, good work. I was in the process of integrating it into a modpack when I ran into a problem which took me a while to figure out:

If tool parts are registered in "tool_parts.json" but their recipes are not registered in "tools.json", then the mod attempts to generate a recipe in the "lobmetalworks_data\data\lobmetalworks\recipes" folder and fails, making the datapack invalid when you try to load a world. I can tell this is the issue because it leaves an empty recipe json.

It isn't really a big deal since it can be worked around with crafttweaker, but I thought I should make you and others aware.

**Comment by lobbienjonsji** [comment]
Thank you, I will look into that!

**Comment by lobbienjonsji** [comment]
I pushed a quick fix. The mod now not only tests if a tool part but also the corresponding tool is registered before generating crafting recipes.

**Comment by 0-Requiem** [comment]
Wow that was fast, thanks!
