### ISSUE TITLE
All generated materials have "MENUS" at the beginning of their names.

### ISSUE THREAD

**Issue by 0-Requiem** [lobbienjonsji/Lobs-Metalworks-Issues#2]
I can't figure out what's causing it, but all generated materials have "MENUS" at the beginning of their names. Probs an extra string that shouldn't be there. I think it has to do with something in the config.

**Comment by lobbienjonsji** [comment]
did you properly name the materials in the en_us.lang file?

**Comment by lobbienjonsji** [comment]
And if yes, can you give me the modlist? Maybe there is some incompatibility with a mod that messes with formatting.

**Comment by 0-Requiem** [comment]
Uh, my bad, I didn't mean to submit the issue yet because I did not check yet to see if the issue was on my part.

**Comment by lobbien** [comment]
ok
